id = "bend2"
name = "Bend2"
version = "0.2.1"
schema_version = 1
authors = ["Eric Fode"]
description = "Bend2 language support"
repository = "https://github.com/ericfode/zed-bend2"

[language_servers.bend2]
name = "Bend2 language server"
languages = ["Bend2"]
language_ids = { Bend2 = "bend2" }

[grammars.bend]
repository = "https://github.com/amaanq/tree-sitter-bend"
rev = "f47602e1511546e2a5b4a76e3553c68c1952ab8f"
