import { build } from 'esbuild';
import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { isBuiltin } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');
const output = path.join(root, '.build/lsp');
const distribution = path.join(root, 'server/dist');
await mkdir(output, { recursive: true });
await mkdir(distribution, { recursive: true });

for (const entry of ['server', 'analysis-worker', 'analyzer']) {
  const result = await build({
    absWorkingDir: root,
    entryPoints: [`server/src/${entry}.ts`],
    outfile: path.join(output, `${entry}.mjs`),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node22',
    metafile: true,
    minify: true,
    lineLimit: 120,
    legalComments: 'inline',
    banner: {
      js: '// Generated by scripts/build-server.mjs. See source and THIRD_PARTY_LICENSES.txt.\n'
        + 'import { createRequire as __createRequire } from "node:module";\n'
        + 'const require = __createRequire(import.meta.url);',
    },
  });
  for (const generated of Object.values(result.metafile.outputs)) {
    for (const dependency of generated.imports) {
      if (dependency.external && !isBuiltin(dependency.path)) {
        throw new Error(`Unbundled runtime dependency: ${dependency.path}`);
      }
    }
  }
}
await cp(path.join(root, 'server/vendor/base.bend'), path.join(output, 'base.bend'));
await cp(path.join(root, 'server/src/launcher.mjs'), path.join(output, 'launcher.mjs'));
const packages = [
  'vscode-jsonrpc',
  'vscode-languageserver',
  'vscode-languageserver-protocol',
  'vscode-languageserver-textdocument',
  'vscode-languageserver-types',
];
let notices = 'Bend compiler and formatter — Apache-2.0\n\n'
  + await readFile(path.join(root, 'server/vendor/LICENSE'), 'utf8');
for (const name of packages) {
  notices += `\n\n${name} — MIT\n\n`
    + await readFile(path.join(root, 'node_modules', name, 'License.txt'), 'utf8');
}
await writeFile(path.join(output, 'THIRD_PARTY_LICENSES.txt'), notices);
for (const name of ['launcher.mjs', 'server.mjs', 'analysis-worker.mjs', 'THIRD_PARTY_LICENSES.txt']) {
  const generated = await readFile(path.join(output, name));
  const destination = path.join(distribution, name);
  if (check) {
    const committed = await readFile(destination);
    if (!committed.equals(generated)) throw new Error(`Stale ${destination}; run npm run build:server.`);
  } else {
    await writeFile(destination, generated);
  }
}
console.log(`Bend2 language server ${check ? 'verified' : 'built'} (Node.js 22+).`);
